### ISSUE TITLE
New NAK Tool idea: 

### ISSUE THREAD

**Issue by nilsdohms** [coderesting/NAKTools#4]
Moin,

Joost hatte die Idee, dass man vielleicht über die NAK-Tools die Merkliste im OPAC speichern könnte.
Im Moment ist diese ja nach jedem ausloggen weg...

Vielleicht ist das ja was für euch :)

**Comment by coderesting** [comment]
Moin Nils,

ich bin momentan im Auslandssemester und muss mal gucken ob ich Zeit dafür finde.
Die Idee klingt aber ziemlich cool 👍.

**Comment by coderesting** [comment]
Moin,
sry für die späte Antwort.
Ich habe mir das OPAC vor einiger Zeit genauer angesehen und leider gemerkt, dass die Merkliste nur über extreme Umwege lokal speicherbar ist.
Das Problem ist, dass ein Buch nicht über eine ID/titel etc. in die Merkliste aufgenommen wird, sondern über den index (1-10) der aktuell angezeigten Seite. Um die Merkliste also nach einer Abmeldung wieder herzustellen, müsste die Extension für jeden Eintrag in der Merkliste eine Suche über das OPAC starten, dann hoffen, dass das erste Ergebnis das gewünschte Buch ist, und eine Anfrage an den Server stellen das Buch mit index 1 (erstes Ergebnis) zur Merkliste hinzuzufügen. Diese Herangehensweise ist meiner Meinung nach viel zu langsam, fehleranfällig und den Aufwand einfach nicht wert.
Falls jemand einen besseren Ansatz herausfindet oder meine Idee doch umsetzten möchte freue ich mich über pull requests aber ansonsten bleibt diese Idee leider erstmal nicht umsetzbar.

Yannick
